[[http]]
domain = "rss.maskdemand.net"
https = true
redirect_trailing_slash = true
redirect_fixed_path = true

[http.timeout]
read = "10s"
read_header = "10s"
idle = "10s"
write = "10s"

[http.max]
header_size = 1048576
body_size = 1048576

[[http.routes]]
path = "GET /"
service = "index"

[[http.routes]]
path = "GET /en"
service = "feed"

[[http.routes]]
path = "GET /zh"
service = "feed-zh"

[[http.routes]]
path = "GET /sources"
service = "sources"
